# Generated by Django 6.0.4 on 2026-04-13 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFurnitureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('color', models.CharField(default='#888888', max_length=7)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='furniture_objects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_furnitures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_width', models.FloatField(default=400)),
                ('room_height', models.FloatField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('preset', 'Preset Furniture'), ('custom', 'Custom Object')], default='preset', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('subtype', models.CharField(max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('width', models.FloatField(default=50)),
                ('height', models.FloatField(default=50)),
                ('length', models.FloatField(default=50)),
                ('angle', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('color', models.CharField(default='#888888', max_length=7)),
                ('visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='planner.customfurnitureobject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_items', to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wall', max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=10)),
                ('angle', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('bearing', models.BooleanField(default=False)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('z_index', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('distance_from_start', models.FloatField(default=0)),
                ('furniture_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='planner.furnitureitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='planner.project')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_items', to='planner.wall')),
            ],
            options={
                'unique_together': {('furniture_item', 'wall')},
            },
        ),
    ]
