# Generated by Django 6.0.4 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfurnitureobject',
            name='length',
        ),
        migrations.RemoveField(
            model_name='furnitureitem',
            name='length',
        ),
        migrations.AddField(
            model_name='furnitureitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ObjectBinding',
        ),
    ]
