# Generated by Django 6.0.4 on 2026-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_customfurnitureobject_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='ignore_overlap',
            field=models.BooleanField(default=False),
        ),
    ]
